Repository edgexfoundry/app-functions-sdk-go, pull requests merged in 2021-08, with the labels that each got.

#931 docs: Update build status badge
  README.md
Labels: documentation

#934 ci: remove the need for a ci specific Dockerfile
  Dockerfile.build
Labels: ci

#935 build: Add back go mod tidy to template Makefile for Depend-a-bot PRs
  app-service-template/Makefile
Labels: 3-high, ci
