Repository edgexfoundry/app-functions-sdk-go, pull requests merged in 2022-11, with the labels that each got.

#1209 docs: Levski Change Log
  CHANGELOG.md
Labels: documentation

#1215 fix: Username may be required when MQTT cert authentication
  pkg/secure/mqttfactory.go
  pkg/secure/mqttfactory_test.go
Labels: bug

#1216 docs: Add recent bug fix to Levski change log
  CHANGELOG.md
Labels: documentation

#1217 ci: automated version changes for OpenAPI version: [2.4.0]
  VERSION
  openapi/v2/app-functions-sdk.yaml
Labels: documentation, ci
