Repository edgexfoundry/app-functions-sdk-go, pull requests merged in 2023-07, with the labels that each got.

#1434 build: Update to latest go-mods
  app-service-template/Attribution.txt
  app-service-template/go.mod
  app-service-template/go.sum
  go.mod
  go.sum
Labels: ci

#1444 feat: fix logic to better error handling when common config is missing when runs in hybrid mode
  app-service-template/go.mod
  app-service-template/go.sum
  go.mod
  go.sum
  internal/app/service.go
  internal/app/triggerfactory.go
  internal/bootstrap/handlers/version.go
  internal/trigger/messagebus/messaging.go
Labels: enhancement

#1447 feat(security): Add authentication hooks to routes (backport)
  Jenkinsfile
  internal/app/service_test.go
  internal/webserver/server.go
  internal/webserver/server_test.go
Labels: hold

#1453 docs: Added 3.0.1 changelog to main branch
  CHANGELOG.md
Labels: documentation
